# Generated by Django 3.1.4 on 2021-01-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projectsp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectSP',
            new_name='ProjectSpanish',
        ),
    ]
