# Generated by Django 3.1.4 on 2021-01-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210112_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspanish',
            name='descripcion',
            field=models.TextField(max_length=1500),
        ),
    ]
