# Generated by Django 3.1.4 on 2021-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_programminglang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='skills/images/')),
            ],
        ),
    ]
